export const url = "https://chat.thewidlarzgroup.com/api/graphiql";
export const wsUrl = "wss://chat.thewidlarzgroup.com/socket";
export const token = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJjaGF0bHkiLCJleHAiOjE2MDU1MjE3MjMsImlhdCI6MTYwMzEwMjUyMywiaXNzIjoiY2hhdGx5IiwianRpIjoiMWY5MWFlOGItYmQzMC00OTYyLWI3ZDQtMDFjNDBhMDcwZDE2IiwibmJmIjoxNjAzMTAyNTIyLCJzdWIiOiIzNDFlOTUwYi05NWI3LTRlODUtODEwNi01MDcxMDU0NGM2YjYiLCJ0eXAiOiJhY2Nlc3MifQ.swL1QZCcGZJunLHxb_ILV3FmbIYajn6U7_DOXEnIbBVCn1jxVl4u9NLJQcB0-LNiAdk2dhGGrL4qVpPamFdQxg";
